### ISSUE TITLE
doesn't work with line-height

### ISSUE THREAD

**Issue by wenzowski** [heygrady/textshadow#9]
When elements have a line-height set, the shadows are not placed correctly in IE9 (possibly in other versions as well).

Workaround: remove all line-height declarations and use `padding-top` and `padding-bottom` on those elements instead.

Fantastic library, greatly appreciated! Thanks!

**Comment by heygrady** [comment]
I'm still looking into it. There's a different quick fix that requires a little less of a compromise. The issue is that the `.ui-text-shadow-copy` is picking up the line-height, and that makes it too tall. The fix is to give the `.ui-text-shadow-copy` a better line-height. Sadly, a line-height of 1em doesn't fix it. But you can measure it in each case that it breaks and fix it.

## Step 1: reset the line-height

Set the line-height of the `.ui-text-shadow-copy` to 1em and measure it's height. The example below is using the Compass mixin and is written in Sass.

``` scss
// output the base CSS classes
@include jquery-text-shadow-base-styles;

// Apply a text-shadow to an element
p {
  font-size: 3em;
  line-height: 2em; // set a line-height that breaks everything
  .ui-text-shadow-copy { line-height: 1em; } // correct for the inherited line-height
  @include jquery-text-shadow( 3px 3px 2px rgba(255, 0, 0, 0.5) ); // apply the text-shadow
}
```

## Step 2: find the correct line-height

You need to measure the height of `.ui-text-shadow-copy` versus the `.ui-text-shadow-original`. The ratio between those two heights is the perfect `line-height` to use for this case. It's usually a number between 1.1em and 1.2em. But's its different for every `font-size`. 

You can get the calculated heights in a number of ways. The easiest way is probably to use Chrome's Web Inspector because it tells you how tall something is if you hover it. Otherwise you could probably apply `background-color` to the different elements and then measure a screenshot in Photoshop.

``` scss
// output the base CSS classes
@include jquery-text-shadow-base-styles;

// Apply a text-shadow to an element
p {
  font-size: 3em;
  line-height: 2em; // set a line-height that breaks everything
  .ui-text-shadow-original {
    opacity: 0.5; // allow the shadow to show through
    background-color: red;  // make the height obvious visually
  }
  .ui-text-shadow-copy {
    line-height: 1em; // correct for the inherited line-height
    background-color: green; // make the height obvious visually
   }
   // don't apply the text-shadow because we don't want to be measuring a blur or any annoying offsets
}
```

Once you have the measurements, it's fairly easy to calculate the `line-height` for the shadow. Below is the math written out in JavaScript to make it easier to understand.

``` js
origHeight = 55; // in pixels
copyHeight = 48; // in pixels
lineHeight = (origHeight / copyHeight) + 'em'; // 1.145833333...em
```

## Step 3: use the correct line-height

So, you need to apply the line-height calculated in step 2. CSS usually doesn't a precision greater than 6, so you can cut off the repeating decimal after 6 units.

``` scss
// output the base CSS classes
@include jquery-text-shadow-base-styles;

// Apply a text-shadow to an element
p {
  font-size: 3em;
  line-height: 2em; // set a line-height that breaks everything
  .ui-text-shadow-copy { line-height: 1.145833em; } // correct for the inherited line-height
  @include jquery-text-shadow( 3px 3px 2px rgba(255, 0, 0, 0.5) ); // apply the text-shadow
}
```

**Comment by heygrady** [comment]
H AH HAHAHAH

There's an even easier way to do it: `line-height: normal`. I need to do some more testing but I think this fixes it. I'll be adding this to the default styles once I confirm it works.

``` scss
// output the base CSS classes
@include jquery-text-shadow-base-styles;

// Apply a text-shadow to an element
p {
  font-size: 3em;
  line-height: 2em; // set a line-height that breaks everything
  .ui-text-shadow-copy { line-height: normal; } // correct for the inherited line-height
  @include jquery-text-shadow( 3px 3px 2px rgba(255, 0, 0, 0.5) ); // apply the text-shadow
}
```
